name: cbil
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - plotly
  - pyyaml
  - notebook 
  - pyodbc 
  - elasticsearch
  - openpyxl
  - fastparquet
  - pytz
  
